version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: blog-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-system-docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: blog-php
    working_dir: /var/www
    env_file:
      - ./blog-back-end/.env
    environment:
      APP_ENV: dev
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./blog-back-end:/var/www:delegated
      # نضع var على Volume مستقل لتفادي مشاكل الصلاحيات عبر نظام الملفات
      - symfony_var:/var/www/var
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-project.ini:ro
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    ports:
      - "8080:80"
    volumes:
      - ./blog-back-end/public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 256M
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./blog-front-end
    container_name: blog-frontend
    working_dir: /app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./blog-front-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - nginx
      - php

  jenkins:
    image: jenkins/jenkins:lts
    container_name: blog-jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8082:8080"   
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
       
volumes:
  mysql_data:
  frontend_node_modules:
  symfony_var:
  jenkins_home:  
